#
# SimplePets Config
# Created by RandomTomato
#
prefix: '&6&lMazlíci'
text-color: '&6'
menu-name: '&8&lMenu mazlíků'
pet-info-menu-name: '&8&lInformace o mazlíkovi'
pet-companion-menu-name: '&8&lMazlíčka vložte doprostřed'
#
# Base Command (The message that is sent when a player runs /pets).
#
pets-message:
- ''
- '        &7✦  &6&lMazlíci /help &7✦'
- ''
- '&6/pets - Základní příkazy pro mazlíčky'
- '&6/pets gui - Otevře menu mazlíčků'
- '&6/pets menu add/remove - přidá nebo oddělá mazlíčka z želvího vejce'
- '&6/pets tokens add/remove/set (player) (amount) - Mění počet hráčových tokenů!'
- '&6/pets companion - otevře menu společníka'
- '&6/pets give (pet) (player) - dá konkrténího mazlíčka určenému hráči'
- ''
#
# General Messages (Various messages that are sent to the player when executing commands).
#
no-permission: 'Nemáš pravomoce na to použít tento příkaz!'
reload: 'Konfigurace načtena'
reload-sound: true
turtle-egg: 'Musíš se dívat na želví vajíčko aby to fungovalo!'
invalid-args: 'Argumenty v příkazu jsou zadány špatně'
same-location: 'Dáváš tento příkaz na stejném místě jako minule'
successful-add: 'Úspěšně jsi vytvořil menu'
successful-remove: 'Úspěšně jsi odstranil menu'
tokens-no-player-found: 'Žádný hráč s títo nickem se na server nikdy nepřipojil!'
tokens-number-convert-error: 'Číslo, které jsi napsal nemůže být použito'
tokens-player-provided: 'Nenapsal jsi hráčovo jméno!'
tokens-no-number-provided: 'Nenapsal jsi žádné číslo'
insufficient-funds: 'Nemáš dostatek financí aby jsi obdržel tokeny!'
insufficient-tokens: 'Nemáš dostatek tokenů, aby jsi si mohl zakoupit tohoto mazlíčka!'
zero-tokens: 'Nemůžeš si zakoupit 0 tokenů'
no-player-online: 'Specifikovaný hráč není v tutu chvíli přihlášen!'
#
# Armorstand Settings (The Title and Subtitle used when adding a clickable menu).
#
armorstand-name: '&6&lMazlíci'
armorstand-lore: '&7Pravým kliknutím otevřete menu'
#
# Pets GUI Item Type
# WARNING: Please do not set any these items to be the same as another as this will cause errors.
#
random-item-type: 'TURTLE_EGG'
common-item-type: 'LIME_STAINED_GLASS_PANE'
rare-item-type: 'LIGHT_BLUE_STAINED_GLASS_PANE'
super-rare-item-type: 'PINK_STAINED_GLASS_PANE'
legendary-item-type: 'YELLOW_STAINED_GLASS_PANE'
mythical-item-type: 'RED_STAINED_GLASS_PANE'
#
# Pet GUI Names
#
random-item-name: '&6&lNáhodný mazlíček'
common-item-name: '&a&lBěžný mazlíček'
rare-item-name: '&b&lVzdácný mazlíček'
super-rare-item-name: '&d&lVelice vzácný mazlíček'
legendary-item-name: '&e&lLegendární mazlíček'
mythical-item-name: '&c&lMýtický mazlíček'
purchase-tokens-item-name: '&6&lZakoupit tokeny'
plus-tokens-item-name: '&6&lPřidat tokeny'
minus-tokens-item-name: '&6&lOdebrat tokeny'
your-stats-name: '&6&lTvoje statistiky'
available-pets-name: '&6&lDostupní mazlíčci'
return-name: '&6&lZpět'
#
# Pet GUI Lores
# WARNING: Placeholders will only work with their respective item (%Běžná_cost% will not work with any other Vzácnost).
#
random-item-lore:
- '&7Cena: %random_cost% Tokenů'
- '&eTokeny obdržíte jako denní odměnu, plnění achievemntů a za odměnu od AT atd!'
- ''
- '&eZakup náhodného mazlíčka!'
common-item-lore:
- '&7Cena: %common_cost% Tokenů'
- '&eTokeny obdržíte jako denní odměnu, plnění achievemntů a za odměnu od AT atd!'
- ''
- '&eZakup náhodného běžného mazlíčka!'
rare-item-lore:
- '&7Cena: %rare_cost% Tokenů'
- '&eTokeny obdržíte jako denní odměnu, plnění achievemntů a za odměnu od AT atd!'
- ''
- '&eZakup náhodného vzdácného mazlíčka!'
super-rare-item-lore:
- '&7Cost: %super_rare_cost% Tokenů'
- '&eTokeny obdržíte jako denní odměnu, plnění achievemntů a za odměnu od AT atd!'
- ''
- '&eZakup náhodného velice vzácného mazlíčka!'
legendary-item-lore:
- '&7Cena: %legendary_cost% Tokenů'
- '&eTokeny obdržíte jako denní odměnu, plnění achievemntů a za odměnu od AT atd!'
- ''
- '&eZakup náhodného legendárního mazlíčka!'
mythical-item-lore:
- '&7Cena: %mythical_cost% Tokenů'
- '&eTokeny obdržíte jako denní odměnu, plnění achievementů, odměnu od AT atd!'
- ''
- '&eZakup náhodného mýtického mazlíčka!'
purchase-tokens-item-lore:
- '&7Počet: %amount%'
- '&7Cena: %cost%'
- ''
- '&eKlikni pro zakoumení %amount% tokenů'
plus-tokens-item-lore:
- '&7&lKliknutím levým: &7+1 Token'
- '&7&lKliknutí pravým: &7+5 Tokenů'
- ''
- '&eLevým nebo pravým přidáte tokeny k vašic celkovým tokenům.!'
minus-tokens-item-lore:
- '&7&lKliknutím levým: &7-1 Token'
- '&7&lKliknutí pravým: &7-5 Tokenů (Musíte mít více než 5!)'
- ''
- '&eLevým nebo pravým odeberete tokeny k vašic celkovým tokenům.!'
your-stats-lore:
- '&7&lTokeny: &7%your_tokens%'
available-pets-lore:
- '&7Prohédněte si schopnosti všech mazlíčků'
- ''
- '&eKliknutím zobrazíte dostupné mazlíčky'
return-lore:
- '&eKliknutím se vrátíte do menu mazlíčků!'
#
# Pet Prices (Change the token cost of a pet's Vzácnost and if players can purchase tokens using in-game cash).
#
random-pet-token-cost: 300
Běžná-pet-token-cost: 50
Vzácná-pet-token-cost: 100
super-Vzácná-pet-token-cost: 200
legendary-pet-token-cost: 500
mythical-pet-token-cost: 1000
enable-token-purchase: false
token-cost: 300
#
# Pet Names (The names that are displayed on the pet heads)
# WARNING: Do not have two pets sharing the same name! This will cause errors
# NOTE: For consistency please keep the colours the same as the rarities
# (This should not be changed unless you are translating into another language).
#
rabbit-name: '&a&lZajíček'
bee-name: '&a&lVčelka'
ladybug-name: '&a&l Beruška'
pig-name: '&a&lPrasátko'
fish-name: '&a&lRybička'
cake-name: '&a&lDortík'
cat-name: '&a&lKoťátko'
hornedbeetle-name: '&b&lBrouček'
babychick-name: '&b&lKuřátko'
villager-name: '&b&lVesničan'
crafting-table-name: '&b&lCrafťátko'
ender-chest-name: '&b&lEnderka'
dog-name: '&b&lŠtěně'
mrpenguin-name: '&d&lTučňák'
magnet-name: '&d&lMagneťák'
enderman-name: '&d&lEnderman'
lion-name: '&e&lLvíče'
giraffe-name: '&e&lŽirafa'
knight-name: '&e&lRytíř'
werewolf-name: '&e&lVlk'
unicorn-name: '&c&lJednorožec'
gamer-name: '&c&lPařan'
#
# Pet Lores (Lores that are displayed under the pet name).
#
rabbit-lore: 
- '&7Akorát správně chlupatý!'
- '&7 '
- '&7Schopnost: &aVyšší skoky'
- '&7Doba znovupoužití schopnosti: &a10s'
- '&7Vzácnost: &aBěžná'
bee-lore: 
- '&7Vskutku velmi pilná!'
- '&7 '
- '&7Schopnost: &aKvětinka'
- '&7Doba znovupoužití schopnosti: &a10s'
- '&7Vzácnost: &aBěžná'
ladybug-lore: 
- '&7Sluníčko, popojdi maličko!'
- '&7 '
- '&7Schopnost: &aRegenerace'
- '&7Doba znovupoužití schopnosti: &a30s'
- '&7Vzácnost: &aBěžná'
pig-lore: 
- '&7Prasečí šunka!'
- '&7 '
- '&7Schopnost: &aŠunka'
- '&7Doba znovupoužití schopnosti: &a30s'
- '&7Vzácnost: &aBěžná'
fish-lore: 
- '&7Ryba je přítel, ne žrádlo!'
- '&7 '
- '&7Schopnost: &aŽábra'
- '&7Doba znovupoužití schopnosti: &a12s'
- '&7Vzácnost: &aBěžná'
cake-lore: 
- '&7Voní šmakózně!'
- '&7 '
- '&7Schopnost: &aCukrová bomba'
- '&7Doba znovupoužití schopnosti: &a30s'
- '&7Vzácnost: &aBěžná'
cat-lore: 
- '&7Kdo tu vystrkuje drápky?!'
- '&7 '
- '&7Schopnost: &aUtéct'
- '&7Doba znovupoužití schopnosti: &a15s'
- '&7Vzácnost: &aBěžná'
hornedbeetle-lore: 
- '&7Tento brouk, je naštvaný brouk!'
- '&7 '
- '&7Schopnost: &bNáraz'
- '&7Doba znovupoužití schopnosti: &b20s'
- '&7Vzácnost: &bVzácná'
babychick-lore: 
- '&7A to kuře krákoře...'
- '&7 '
- '&7Schopnost: &bPírko'
- '&7Doba znovupoužití schopnosti: &b10s'
- '&7Vzácnost: &bVzácná'
villager-lore: 
- '&7Hmmmmm......'
- '&7 '
- '&7Schopnost: &bObchod'
- '&7Doba znovupoužití schopnosti: &b30s'
- '&7Vzácnost: &bVzácná'
crafting-table-lore: 
- '&7Copak si dnes vyrobím??'
- '&7 '
- '&7Schopnost: &bStavitel'
- '&7Doba znovupoužití schopnosti: &b10s'
- '&7Vzácnost: &bVzácná'
ender-chest-lore: 
- '&7Ulož si své předměty!'
- '&7 '
- '&7Schopnost: &bTruhla'
- '&7Doba znovupoužití schopnosti: &b30s'
- '&7Vzácnost: &bVzácná'
dog-lore:
- '&7Nejlepší přítel člověka!'
- '&7 '
- '&7Schopnost: &bHaf'
- '&7Doba znovupoužití schopnosti: &b60s'
- '&7Vzácnost: &bVzácná'
mrpenguin-lore: 
- '&7Tučňáci vynalezli koulovačku!'
- '&7 '
- '&7Schopnost: &dBum'
- '&7Doba znovupoužití schopnosti: &d10s'
- '&7Vzácnost: &dVelice vzácná'
magnet-lore: 
- '&7Opaky se přitahují.'
- '&7 '
- '&7Schopnost: &dMagnet'
- '&7Doba znovupoužití schopnosti: &d20s'
- '&7Vzácnost: &dVelice vzácná'
enderman-lore: 
- '&7Skok sem, skok tam!'
- '&7 '
- '&7Schopnost: &dTeleport'
- '&7Doba znovupoužití schopnosti: &d60s'
- '&7Vzácnost: &dVelice vzácná'
lion-lore: 
- '&7Král zvířat při tvém boku'
- '&7 '
- '&7Schopnost: &eŘev'
- '&7Doba znovupoužití schopnosti: &e60s'
- '&7Vzácnost: &eLegendární'
giraffe-lore: 
- '&7Vidí až do korun stromů'
- '&7 '
- '&7Schopnost: &ePozření'
- '&7Doba znovupoužití schopnosti: &e5s'
- '&7Vzácnost: &eLegendární'
knight-lore: 
- '&7Střeží tě jako oko v hlavě?!'
- '&7 '
- '&7Schopnost: &ePokřik'
- '&7Doba znovupoužití schopnosti: &e120s'
- '&7Vzácnost: &eLegendární'
werewolf-lore:
- '&7Co takhle mít instinkt jako vlk!'
- '&7 '
- '&7Schopnost: &eLov'
- '&7Doba znovupoužití schopnosti: &e40s'
- '&7Vzácnost: &eLegendární'
unicorn-lore: 
- '&7I jeden roh stačí.'
- '&7 '
- '&7Schopnost: &cLétaní'
- '&7Doba znovupoužití schopnosti: &c240s'
- '&7Vzácnost: &cMýtickál'
gamer-lore: 
- '&7Blbý lag.'
- '&7 '
- '&7Schopnost: &lLag'
- '&7Doba znovupoužití schopnosti: &c240s'
- '&7Vzácnost: &cMýtickál'
#
# Schopnost Cooldown Times (Time in seconds)
# WARNING: To prevent errors DO NOT set the Unicorn or Gamer pet to be lower than 20s (Gamer ability recommended to be 240s+ as if this ability is used often it can cause lag)
#
rabbit-cooldown: 10
bee-cooldown: 10
ladybug-cooldown: 30
pig-cooldown: 30
fish-cooldown: 12
cake-cooldown: 30
cat-cooldown: 15
hornedbeetle-cooldown: 20
babychick-cooldown: 10
villager-cooldown: 30
crafting-table-cooldown: 10
ender-chest-cooldown: 30
dog-cooldown: 60
mrpenguin-cooldown: 10
magnet-cooldown: 20
enderman-cooldown: 60
lion-cooldown: 60
giraffe-cooldown: 5
knight-cooldown: 120
werewolf-cooldown: 40
unicorn-cooldown: 240
gamer-cooldown: 240
#
# Pet Hot Bar Messages (Messages that are displayed on the hotbar when a Schopnost is used).
#
rabbit-hotbar: '&a&lHopsá po tvém boku!'
bee-hotbar: '&a&lTvoje včelka ti dala květinku!'
ladybug-hotbar: '&a&lSlunéčko, popolez maličko!'
pig-hotbar: '&a&lNechť tě provází šunka!'
fish-hotbar: '&a&lUmíš dýchat pod vodou!'
cake-hotbar: '&a&lŇam, Ňam, Ňam'
cat-hotbar: '&a&lMňau!'
hornedbeetle-hotbar: '&b&lBrouk tě kousl do zadku a ty jsi se rozeběhl!'
babychick-hotbar: '&b&lPlachtit teda umí'
villager-hotbar: '&b&lSleva 50%'
crafting-table-hotbar: '&b&lSprávný pomocnk kutilů'
ender-chest-hotbar: '&b&lTvor který je propojen s tajenmným místem'
dog-hotbar: '&b&lHaf'
mrpenguin-hotbar: '&d&lTu máš!'
magnet-hotbar: '&d&lZzzzzzzzz'
enderman-hotbar: '&d&lSkok sem, skok tam..'
lion-hotbar: '&e&lTvůje lvíče zabilo nejblížší zvíře'
giraffe-hotbar: '&e&lTvoje žirafa snědla listí'
knight-hotbar: '&e&lPřeze mě nikdo neprojde!'
werewolf-hotbar: '&e&lVrrrr'
unicorn-hotbar: '&c&lA teď můžeš létat!'
gamer-hotbar: '&c&lAktivace hacků!!!'
#
# Pet Companion Names
#
rabbit-companion-name: '&aZajíček'
bee-companion-name: '&aVčelka'
ladybug-companion-name: '&aBeruška'
pig-companion-name: '&aPrasátkot'
fish-companion-name: '&aRybička'
cake-companion-name: '&aDortík'
cat-companion-name: '&aKoťátko'
hornedbeetle-companion-name: '&bBrouček'
babychick-companion-name: '&bKuřátko'
villager-companion-name: '&bVesničan'
crafting-table-companion-name: '&bCrafťátko'
ender-chest-companion-name: '&bEnderka'
dog-companion-name: '&bŠtěně'
mrpenguin-companion-name: '&dTučňák'
magnet-companion-name: '&dMagneťák'
enderman-companion-name: '&dEnderman'
lion-companion-name: '&eLvíče'
giraffe-companion-name: '&eŽirafa'
knight-companion-name: '&eRytíř'
werewolf-companion-name: '&eVlk'
unicorn-companion-name: '&cJednorožec'
gamer-companion-name: '&cPařan'